title: Jhalak Surve
logo: /assets/img/profile_picture.png
description: A graduate student specializing in data science and AI, I bring a strong foundation in machine learning, statistical analysis, and data visualization. Proficient in Python and skilled in leveraging data-driven insights to solve complex problems. Eager to apply theoretical knowledge and hands-on experience in real-world projects, contributing to innovative solutions and advancements in the field of data science.
show_downloads: true
theme: jekyll-theme-minimal
